# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171223_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium_url',
            field=models.URLField(null=True),
        ),
    ]
