# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_medium_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../../images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medium_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
