# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180102_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medium_url',
        ),
        migrations.AddField(
            model_name='post',
            name='medium_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='text_preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
