# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180102_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
